name: Build Balena Disk Images
on: workflow_dispatch

jobs:
  run-cli-command:
    strategy:
      matrix:
        board: ['pi1', 'pi2', 'pi3', 'pi4']
    runs-on: ubuntu-20.04
    steps:
      - uses: balena-io-examples/community-cli-action@1.0.0
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          balena_cli_version: 18.2.2
          balena_cli_commands: >
            whoami;
            envs --fleet screenly_ose/anthias-${{ matrix.board }} --config;

